### ISSUE TITLE
Ernest the chicken quest

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [2006rs/singleplayer#10]
When in the doors section, pulled A and B down to enter first door, they are semi-open as they should be, but I can't get through them. Tried walking around them, relogging, nothing worked.

**Comment by Mige5** [comment]
Yeah, I have had this issue for several years, for some weird reason the door only works from the other side. I have had tons of ideas about the issue, but the issue just doesnt seem to go away whatever I try.

**Comment by SlyJacobTheBeast** [comment]
Is there a way to finish the quest? I would suggest having the door to the item opened already, so atleast it's doable.

**Comment by Mige5** [comment]
hmm.. I think I could add item spawn outside the door as a temporary fix.
