### ISSUE TITLE
Wildy Bots are still in p2p locations

### ISSUE THREAD

**Issue by DomeFossilx** [2006rs/singleplayer#9]
![Screenshot_1](https://user-images.githubusercontent.com/54909553/64280592-6eb80400-cf1f-11e9-9031-39641c643b8e.png)

**Comment by Mige5** [comment]
Was a bit hard to see if they really are in p2p tile or just in the very corner of f2p area, but anyway theres a small change in code in next update.

**Comment by NeedingName** [comment]
There are also bots spawning inside the KBD lair gates. They can be attacked with ranged or magic though, unlike bots in the lava maze area.

**Comment by Mige5** [comment]
> There are also bots spawning inside the KBD lair gates. They can be attacked with ranged or magic though, unlike bots in the lava maze area.

This with patch 1.6.4?

**Comment by NeedingName** [comment]
Yes with patch 1.6.4 but I turned the wildy bot numbers way up so maybe that causes issues!

**Comment by Mige5** [comment]
Oh yea, found 1 mistake. Should work properly with next update.

**Comment by Mige5** [comment]
I think this is working fine in patch 1.7 so closing this now.
